# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Generic


class _Database(_Generic):
    _type = "database"
    _icon_dir = "resources/generic/database"


class Cassandra(_Database):
    _icon = "cassandra.png"


class Database(_Database):
    _icon = "database.png"


class MYSQL(_Database):
    _icon = "mysql.png"


class Postgres(_Database):
    _icon = "postgres.png"


# Aliases
