# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Generic


class _Machine(_Generic):
    _type = "machine"
    _icon_dir = "resources/generic/machine"


class LAPTOP(_Machine):
    _icon = "laptop.png"


class SERVER(_Machine):
    _icon = "server.png"


# Aliases
