# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Generic


class _Services(_Generic):
    _type = "services"
    _icon_dir = "resources/generic/services"


class Blackflag(_Services):
    _icon = "blackflag.png"


class Consul(_Services):
    _icon = "consul.png"


class Github(_Services):
    _icon = "github.png"


class Golang(_Services):
    _icon = "golang.png"


class Java(_Services):
    _icon = "java.png"


class Service(_Services):
    _icon = "service.png"


class Sidecar(_Services):
    _icon = "sidecar.png"


# Aliases
